export const userActionTypes = {
    FETCH_LISTS_REQUEST: 'USER/FETCH_LISTS_REQUEST',
    FETCH_LISTS_SUCCESS: 'USER/FETCH_LISTS_SUCCESS',
    FETCH_LISTS_FAILURE: 'USER/FETCH_LISTS_FAILURE',

    FETCH_LIST_CONTENT_REQUEST: 'USER/FETCH_LIST_CONTENT_REQUEST',
    FETCH_LIST_CONTENT_SUCCESS: 'USER/FETCH_LIST_CONTENT_SUCCESS',
    FETCH_LIST_CONTENT_FAILURE: 'USER/FETCH_LIST_CONTENT_FAILURE',

};
